-- ─────────────────────────────────────────────────────────────────────────────
-- KASRAT — readiness_scores table
-- Daily Traffic-Light Recovery Assessment
-- Run in Supabase SQL Editor after schema.sql
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.readiness_scores (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  date        date NOT NULL,
  sleep       int  NOT NULL CHECK (sleep BETWEEN 1 AND 5),
  soreness    int  NOT NULL CHECK (soreness BETWEEN 1 AND 5),
  energy      int  NOT NULL CHECK (energy BETWEEN 1 AND 5),
  stress      int  NOT NULL CHECK (stress BETWEEN 1 AND 5),
  motivation  int  NOT NULL CHECK (motivation BETWEEN 1 AND 5),
  total       int  NOT NULL,
  label       text NOT NULL CHECK (label IN ('green', 'yellow', 'red')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date)
);

CREATE INDEX IF NOT EXISTS readiness_scores_user_id_idx ON public.readiness_scores(user_id);
CREATE INDEX IF NOT EXISTS readiness_scores_date_idx    ON public.readiness_scores(date);

ALTER TABLE public.readiness_scores ENABLE ROW LEVEL SECURITY;

-- Allow each user to read their own rows
CREATE POLICY "readiness_scores_select"
  ON public.readiness_scores FOR SELECT
  USING (auth.uid() = user_id);

-- Allow each user to insert their own rows
CREATE POLICY "readiness_scores_insert"
  ON public.readiness_scores FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Allow each user to update their own rows (e.g. retake same day)
CREATE POLICY "readiness_scores_update"
  ON public.readiness_scores FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Allow each user to delete their own rows
CREATE POLICY "readiness_scores_delete"
  ON public.readiness_scores FOR DELETE
  USING (auth.uid() = user_id);

-- Allow client to supply its own id (offline-first sync)
ALTER TABLE public.readiness_scores ALTER COLUMN id SET GENERATED BY DEFAULT;
